// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUserCoupon = "user_coupon"

// UserCoupon mapped from table <user_coupon>
type UserCoupon struct {
	UserCouponID int32  `gorm:"column:user_coupon_id;type:int(11);primaryKey;autoIncrement:true" json:"user_coupon_id"`
	CouponID     int32  `gorm:"column:coupon_id;type:int(11);not null" json:"coupon_id"`
	UserID       int32  `gorm:"column:user_id;type:int(11);not null" json:"user_id"`
	Status       int    `gorm:"column:status;type:tinyint(4);not null" json:"status"` // 优惠券状态，1｜待使用，2｜已使用，3｜已过期
	ShopID       int32  `gorm:"column:shop_id;type:int(11);not null" json:"shop_id"`  // 冗余coupon表店铺id
	CreatedAt    Time   `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    Time   `gorm:"column:updated_at;type:datetime" json:"updated_at"`
	Coupon       Coupon `gorm:"hasone:coupon;foreignKey:CouponID;joinForeignKey:CouponID;joinReferences:CouponID" json:"coupon"`
}

// TableName UserCoupon's table name
func (*UserCoupon) TableName() string {
	return TableNameUserCoupon
}
